// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrQFyk225HWbO5QPGdR5gB1QCBBcDiSCE',
    appId: '1:208263614673:web:2e024251d7f118f124f5f0',
    messagingSenderId: '208263614673',
    projectId: 'b2b-exchange',
    authDomain: 'b2b-exchange.firebaseapp.com',
    storageBucket: 'b2b-exchange.appspot.com',
    measurementId: 'G-WBXKY0EFNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZkC11paSsaUiqIaNXCzXG7nVdU_i7T1o',
    appId: '1:208263614673:android:b1a3742ab2c13f4124f5f0',
    messagingSenderId: '208263614673',
    projectId: 'b2b-exchange',
    storageBucket: 'b2b-exchange.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-0y03LIepOUB_6_7U-_6lyQ3_UYIGvY',
    appId: '1:208263614673:ios:d7902ff2d0c4c08324f5f0',
    messagingSenderId: '208263614673',
    projectId: 'b2b-exchange',
    storageBucket: 'b2b-exchange.appspot.com',
    androidClientId: '208263614673-3q17bso7jcok9pm6p53l79rdpecs86hi.apps.googleusercontent.com',
    iosClientId: '208263614673-vmktr15cpe044pqe1jn860d1713stsif.apps.googleusercontent.com',
    iosBundleId: 'com.example.b2b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ-0y03LIepOUB_6_7U-_6lyQ3_UYIGvY',
    appId: '1:208263614673:ios:d7902ff2d0c4c08324f5f0',
    messagingSenderId: '208263614673',
    projectId: 'b2b-exchange',
    storageBucket: 'b2b-exchange.appspot.com',
    androidClientId: '208263614673-3q17bso7jcok9pm6p53l79rdpecs86hi.apps.googleusercontent.com',
    iosClientId: '208263614673-vmktr15cpe044pqe1jn860d1713stsif.apps.googleusercontent.com',
    iosBundleId: 'com.example.b2b',
  );
}
